### PR TITLE
Bash-scripting-enabling entry script.

### PR DESCRIPTION
**Pull request by artospaj**
This entry script allows to run some bash scripts/commands. When command begins with "render", then the command is passed to original `/dcv/bin/dcv` script.

### CODE REVIEW

**Comment by artospaj** [comment]
@jubianchi any comments?

**Comment by jubianchi** [comment]
@artospaj the patch is OK. But I'm wondering what the benefit of such a feature is?

What about using `--entrypoint` option of the `run` command to override the entrypoint when it's required ?

**Comment by artospaj** [comment]
@jubianchi Sometimes you use the image in tools that doesn't give you any chance to customize the run, i.e. by overriding entry point. The one I used is GitLab CI's multi runner which requires the Image to be able to run command-line scripts. More about it here: https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/blob/master/docs/executors/docker.md#the-entrypoint

Writing entrypoints as scripts that can execute either command-line scripts and run custom binary has become standard solution... or I just see it this way :)

**Comment by jubianchi** [comment]
@artospaj Fine, thanks for the details!

LGTM :shipit:

**Comment by jubianchi** [comment]
@artospaj here is the release:

* https://github.com/pmsipilot/docker-compose-viz/releases/tag/1.1.0
* https://hub.docker.com/r/pmsipilot/docker-compose-viz/tags/

**Pull request merged**
